geocoding:
  geocoding_url: "https://api.geoapify.com/v1/geocode/search"
  acceptable_cities: [warszawa, gdansk, krakow, wroclaw]
  street_prefixes: [
    "ul.",
    "al.",
    "os.",
    "gen.",
    "prof.",
    "prezydenta",
    "osiedle",
    "aleja",
    "pl.",
    "ulica",
    "os",
    "plk.",
    "generala",
    "ksiedza",
    "marszalka"
  ]